// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ8l4CPspO2cdntp5nC2Hmy0Xh07gOcYI',
    appId: '1:237151616877:web:4beb44bfbe3d464e0ee464',
    messagingSenderId: '237151616877',
    projectId: 'studysnap-8be5f',
    authDomain: 'studysnap-8be5f.firebaseapp.com',
    storageBucket: 'studysnap-8be5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44xChg9A0su0RbXxAKZyywvKsAoBmmnk',
    appId: '1:237151616877:android:3fc7bd9a5110fbe20ee464',
    messagingSenderId: '237151616877',
    projectId: 'studysnap-8be5f',
    storageBucket: 'studysnap-8be5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPMKRRXj5KKkR4fpxnRKXs2EXXIismO8',
    appId: '1:237151616877:ios:ea0e358e1a41165e0ee464',
    messagingSenderId: '237151616877',
    projectId: 'studysnap-8be5f',
    storageBucket: 'studysnap-8be5f.appspot.com',
    iosBundleId: 'com.example.quizet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApPMKRRXj5KKkR4fpxnRKXs2EXXIismO8',
    appId: '1:237151616877:ios:648682607252508c0ee464',
    messagingSenderId: '237151616877',
    projectId: 'studysnap-8be5f',
    storageBucket: 'studysnap-8be5f.appspot.com',
    iosBundleId: 'com.example.quizet.RunnerTests',
  );
}
